import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | DXBmovies",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-12 text-sm leading-relaxed text-text-secondary">
      <Link href="/login" className="mb-8 inline-block text-xs text-primary hover:underline">
        Back
      </Link>

      <h1 className="mb-6 text-2xl font-bold text-white">Terms of Service</h1>
      <p className="mb-4 text-xs text-text-secondary">Last updated: June 2026</p>

      <section className="space-y-6">
        <div>
          <h2 className="mb-2 font-semibold text-white">1. Acceptance</h2>
          <p>
            By accessing or using DXBmovies ("the Service"), you agree to be bound by
            these Terms. If you do not agree, do not use the Service.
          </p>
        </div>

        <div>
          <h2 className="mb-2 font-semibold text-white">2. Who Can Use DXBmovies</h2>
          <p>
            You must have a valid Google account to sign in. The Service is intended
            for personal, non-commercial use only. You are responsible for all
            activity on your account.
          </p>
        </div>

        <div>
          <h2 className="mb-2 font-semibold text-white">3. What We Provide</h2>
          <p>
            DXBmovies offers AI-powered movie recommendations, a conversational
            companion, and tools to track your watchlist and preferences. Movie data
            is sourced from The Movie Database (TMDB). We do not host or stream any
            video content.
          </p>
        </div>

        <div>
          <h2 className="mb-2 font-semibold text-white">4. Your Data</h2>
          <p>
            We store your preferences, watchlist, reactions, and conversation history
            to personalize your experience. We do not sell your data to third parties.
            See our{" "}
            <Link href="/privacy" className="text-primary underline underline-offset-2">
              Privacy Policy
            </Link>{" "}
            for details.
          </p>
        </div>

        <div>
          <h2 className="mb-2 font-semibold text-white">5. Acceptable Use</h2>
          <p>
            You agree not to misuse the Service, attempt to gain unauthorized access,
            scrape content, or use the AI companion to generate harmful content.
            We reserve the right to suspend accounts that violate these terms.
          </p>
        </div>

        <div>
          <h2 className="mb-2 font-semibold text-white">6. AI Recommendations</h2>
          <p>
            Recommendations are generated by AI and are for entertainment purposes
            only. We do not guarantee accuracy or availability of any suggested
            content on any streaming platform.
          </p>
        </div>

        <div>
          <h2 className="mb-2 font-semibold text-white">7. Changes</h2>
          <p>
            We may update these Terms at any time. Continued use of the Service after
            changes constitutes acceptance of the updated Terms.
          </p>
        </div>

        <div>
          <h2 className="mb-2 font-semibold text-white">8. Contact</h2>
          <p>
            Questions? Reach us at{" "}
            <a href="mailto:hello@dxbmovies.com" className="text-primary underline underline-offset-2">
              hello@dxbmovies.com
            </a>
          </p>
        </div>
      </section>
    </main>
  );
}
